apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-resource-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-resource-demo
  template:
    metadata:
      labels:
        app: no-resource-demo
    spec:
      containers:
      - name: nginx
        image: nginx
